name: pipe-spring-build flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          images: ${{ vars.DOCKER_USERNAME }}/pipelocux
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ vars.DOCKER_PASSWORD }}
